name: oral-cancer-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - jupyterlab
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - keras
  - opencv
  - pillow
  - ipykernel
  - notebook
  - pip
  - pip:
      - albumentations
      - pytorch-lightning
      - wandb
